apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "webhook-app.fullname" . }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "webhook-app.fullname" . }}
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
